# Generated by Django 5.2.7 on 2025-11-22 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scan_type', models.CharField(choices=[('quick', 'Quick Scan (Top 100 ports)'), ('standard', 'Standard Scan (Top 1000 ports)'), ('deep', 'Deep Scan (All 65535 ports)'), ('custom', 'Custom Scan')], default='standard', max_length=20)),
                ('port_range', models.CharField(default='1-1000', help_text='e.g., 1-1000 or 80,443,8080', max_length=255)),
                ('enable_service_detection', models.BooleanField(default=True)),
                ('enable_os_detection', models.BooleanField(default=False)),
                ('enable_vuln_detection', models.BooleanField(default=True)),
                ('timeout', models.IntegerField(default=300, help_text='Timeout in seconds')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target', models.CharField(help_text='IP address, domain, or CIDR range', max_length=255)),
                ('target_type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain Name'), ('range', 'IP Range (CIDR)')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('target', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('current_phase', models.CharField(blank=True, help_text='Current scan phase', max_length=100)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_ports_scanned', models.IntegerField(default=0)),
                ('open_ports_found', models.IntegerField(default=0)),
                ('vulnerabilities_found', models.IntegerField(default=0)),
                ('critical_vulns', models.IntegerField(default=0)),
                ('high_vulns', models.IntegerField(default=0)),
                ('medium_vulns', models.IntegerField(default=0)),
                ('low_vulns', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.scanconfiguration')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_scans', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='scanner.scantarget')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('vuln_type', models.CharField(choices=[('port', 'Open Port'), ('service', 'Service Vulnerability'), ('config', 'Misconfiguration'), ('cve', 'Known CVE'), ('protocol', 'Insecure Protocol'), ('auth', 'Weak Authentication'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=20)),
                ('cvss_score', models.FloatField(blank=True, help_text='CVSS Score (0-10)', null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=10)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('service_version', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('impact', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('cve_id', models.CharField(blank=True, help_text='CVE ID if applicable', max_length=50)),
                ('cve_url', models.URLField(blank=True)),
                ('raw_output', models.TextField(blank=True, help_text='Raw scanner output')),
                ('evidence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanner.scanjob')),
            ],
            options={
                'ordering': ['-severity', '-cvss_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(default='tcp', max_length=10)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('filtered', 'Filtered')], max_length=20)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('service_version', models.CharField(blank=True, max_length=255)),
                ('banner', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_results', to='scanner.scanjob')),
            ],
            options={
                'ordering': ['port'],
                'unique_together': {('scan_job', 'port', 'protocol')},
            },
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['-created_at'], name='scanner_sca_created_faca24_idx'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['status', '-created_at'], name='scanner_sca_status_bc18b8_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['scan_job', 'severity'], name='scanner_vul_scan_jo_037ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['severity', '-cvss_score'], name='scanner_vul_severit_f74195_idx'),
        ),
    ]
