# Generated by Django 4.2.7 on 2026-05-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_remove_vulnerability_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='aggregate_risk_score',
            field=models.FloatField(default=0.0, help_text='Aggregated risk posture score (0-10)'),
        ),
    ]
