# Generated by Django 4.2.7 on 2026-05-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_scanjob_aggregate_risk_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='portscanresult',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portscanresult',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portscanresult',
            name='observation_count',
            field=models.IntegerField(default=1, help_text='Number of times this port/service was observed'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='observation_count',
            field=models.IntegerField(default=1, help_text='Number of times this finding was observed'),
        ),
    ]
