# Generated by Django 4.2.7 on 2026-05-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_portscanresult_first_seen_portscanresult_last_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portscanresult',
            name='recurring',
            field=models.BooleanField(default=False, help_text='Indicates if this port was previously resolved but has now reappeared open'),
        ),
        migrations.AddField(
            model_name='portscanresult',
            name='resolved',
            field=models.BooleanField(default=False, help_text='Indicates if the port scan result was resolved (closed/filtered) in a subsequent scan'),
        ),
        migrations.AddField(
            model_name='portscanresult',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the resolution was first verified', null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='recurring',
            field=models.BooleanField(default=False, help_text='Indicates if this exposure was previously resolved but has now reappeared'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='resolved',
            field=models.BooleanField(default=False, help_text='Indicates if the exposure was resolved in a subsequent scan'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the resolution was first verified', null=True),
        ),
    ]
