# Generated by Django 4.2.7 on 2026-05-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_portscanresult_recurring_portscanresult_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portscanresult',
            name='is_suppressed',
            field=models.BooleanField(default=False, help_text='True if manually suppressed by an analyst'),
        ),
        migrations.AddField(
            model_name='portscanresult',
            name='lifecycle_state',
            field=models.CharField(choices=[('active', 'Active'), ('recurring', 'Recurring'), ('resolved', 'Resolved'), ('suppressed', 'Suppressed')], default='active', help_text='Operational lifecycle state of the port exposure', max_length=20),
        ),
        migrations.AddField(
            model_name='portscanresult',
            name='priority_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='Port priority index (0-100)'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='analyst_annotation',
            field=models.TextField(blank=True, help_text='Analyst notes and tracking comments'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='investigation_state',
            field=models.CharField(choices=[('open', 'Open'), ('observed', 'Observed'), ('investigating', 'Investigating'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved')], default='open', help_text='Analyst workflow investigation status', max_length=20),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='is_suppressed',
            field=models.BooleanField(default=False, help_text='True if manually suppressed by an analyst'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='lifecycle_state',
            field=models.CharField(choices=[('active', 'Active'), ('recurring', 'Recurring'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('suppressed', 'Suppressed')], default='active', help_text='Operational lifecycle state of the exposure', max_length=20),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='priority_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='Urgency prioritization index (0-100)'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='reappeared_count',
            field=models.IntegerField(default=0, help_text='Number of times this exposure reappeared after resolution'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='remediation_note',
            field=models.TextField(blank=True, help_text='Mitigation and remediation plans'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='suppressed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when manually suppressed', null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='suppressed_reason',
            field=models.TextField(blank=True, help_text='Justification provided by the analyst for suppression'),
        ),
    ]
