# Generated by Django 4.2.7 on 2026-05-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_portscanresult_is_suppressed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservatoryHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('duration_ms', models.FloatField(help_text='Execution latency in milliseconds')),
                ('status', models.CharField(default='success', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Diagnostic context or error notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
