# Generated by Django 4.2.7 on 2026-05-19 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_observatoryhealthlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=500)),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scanner.scanjob')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
