# Generated by Django 4.2.7 on 2026-05-19 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_scanlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanjob',
            name='celery_task_id',
        ),
    ]
