# Generated by Django 4.2.7 on 2026-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('scan_initiated', 'Scan Initiated'), ('scan_completed', 'Scan Completed'), ('scan_failed', 'Scan Failed'), ('report_generated', 'Report Generated'), ('report_exported', 'Report Exported'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_signup', 'User Account Created')], max_length=50),
        ),
    ]
