# Generated by Django 4.2.7 on 2026-05-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_export_reports',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('scan_initiated', 'Scan Initiated'), ('scan_completed', 'Scan Completed'), ('scan_failed', 'Scan Failed'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_signup', 'User Account Created'), ('user_deleted', 'User Account Decommissioned'), ('user_updated', 'User Account Modified'), ('security_event', 'Security Alert / Validation Failure')], max_length=50),
        ),
    ]
