"""
Reports app views
"""
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import FileResponse, Http404, HttpResponseForbidden
from apps.scanner.models import ScanJob
from .models import Report, ExportHistory
from .generators import pdf_generator, csv_generator, json_generator
from apps.accounts.decorators import analyst_or_admin
import os


@login_required
def report_list(request):
    """List all reports generated by the user"""
    reports = Report.objects.filter(generated_by=request.user).select_related('scan_job', 'scan_job__target')
    
    context = {'reports': reports}
    return render(request, 'reports/report_list.html', context)


@login_required
@analyst_or_admin
def report_generate(request, scan_id):
    """Generate a report from a scan"""
    scan = get_object_or_404(ScanJob, id=scan_id, initiated_by=request.user)

    if not request.user.can_export_reports:
        messages.error(request, "You don't have permission to generate reports.")
        return redirect('scan_detail', scan_id=scan_id)
    
    if scan.status != 'completed':
        messages.error(request, "Can only generate reports for completed scans.")
        return redirect('scan_detail', scan_id=scan_id)
    
    if request.method == 'POST':
        report_format = request.POST.get('format', 'pdf')
        
        # Generate the report based on format
        if report_format == 'pdf':
            file_path = pdf_generator.generate_pdf_report(scan, request.user)
        elif report_format == 'csv':
            file_path = csv_generator.generate_csv_report(scan, request.user)
        elif report_format == 'json':
            file_path = json_generator.generate_json_report(scan, request.user)
        else:
            messages.error(request, "Invalid report format.")
            return redirect('scan_detail', scan_id=scan_id)
        
        if file_path:
            messages.success(request, f"Report generated successfully in {report_format.upper()} format!")
            # Redirect to report list or download
            return redirect('report_list')
        else:
            messages.error(request, "Failed to generate report.")
            return redirect('scan_detail', scan_id=scan_id)
    
    context = {'scan': scan}
    return render(request, 'reports/report_generate.html', context)


@login_required
def report_download(request, report_id):
    """Download a generated report"""
    report = get_object_or_404(Report, id=report_id, generated_by=request.user)

    if not request.user.can_export_reports:
        return HttpResponseForbidden("You don't have permission to download reports.")
    
    if not report.file_path or not os.path.exists(report.file_path):
        raise Http404("Report file not found.")
    
    # Log the export
    ExportHistory.objects.create(
        report=report,
        exported_by=request.user,
        ip_address=_get_client_ip(request),
    )
    
    # Serve the file
    return FileResponse(
        open(report.file_path, 'rb'),
        as_attachment=True,
        filename=report.filename
    )


def _get_client_ip(request):
    """Get client IP address from request"""
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip
