# Generated by Django 5.2.7 on 2025-11-22 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('format', models.CharField(choices=[('pdf', 'PDF Document'), ('csv', 'CSV Export'), ('json', 'JSON Export'), ('html', 'HTML Report')], max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('executive_summary', models.TextField(blank=True)),
                ('total_findings', models.IntegerField(default=0)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='scanner.scanjob')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_history', to='reports.report')),
            ],
            options={
                'verbose_name_plural': 'Export histories',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['-generated_at'], name='reports_rep_generat_fa1e6b_idx'),
        ),
    ]
